package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"

	"github.com/Foxtrot-14/FitRang/notification-service/graph/model"
)

// MarkMessageAsRead is the resolver for the markMessageAsRead field.
func (r *mutationResolver) MarkMessageAsRead(ctx context.Context, messageID string) (*model.Message, error) {
	return r.MessageService.MarkMessageAsRead(ctx, messageID)
}

// GetMessages is the resolver for the getMessages field.
func (r *queryResolver) GetMessages(ctx context.Context) ([]*model.Message, error) {
	return r.MessageService.GetMessages(ctx)
}

// GetUnreadMessages is the resolver for the getUnreadMessages field.
func (r *queryResolver) GetUnreadMessages(ctx context.Context) ([]*model.Message, error) {
	return r.MessageService.GetUnreadMessages(ctx)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
